branch-defaults:
  default:
    environment: myweb
    group_suffix: null
global:
  application_name: deploy
  branch: null
  default_ec2_keyname: aws-eb3
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
